### ISSUE TITLE
Some error types don't match the specs

### ISSUE THREAD

**Issue by twuebi** [hansetag/iceberg-catalog#306]
- [ ] `NamespaceNotFound` -> `NoSuchNamespaceException`

**Comment by ndrluis** [comment]
Hello @twuebi, could you elaborate on what the problem is with Lakekeeper? I'm a bit confused about the issue.

**Comment by twuebi** [comment]
Hi @ndrluis, it's been a while, I think I created this issue after running the rest compatibility suite of the Java iceberg repo against lakekeeper. A lot of their tests were failing but not due to functional problems but due to the error code not matching what Java would expect. 

Lakekeeper could try to align itself with what the test suite expects. In some cases it wouldn't make a difference in others it makes a difference in what exception a client will see which can or cannot be misleading.

I think in the example above, trying to read a table from a non-existing namespace will produce a table does not exist error instead of a name space does not exist error due to error code not matching the Java expectation.

**Comment by ndrluis** [comment]
In some tests, I got this kind of error that I don't know if it makes sense to fix, like these. @twuebi @c-thiel @mooori what do you think about these tests?

```
Iceberg REST Compatibility Kit > JUnit Jupiter > RESTCompatibilityKitViewCatalogTests > renameTableTargetAlreadyExistsAsView() FAILED
    java.lang.AssertionError:
    Expecting throwable message:
      "Error renaming Table"
    to contain:
      "Cannot rename ns.table to ns.view. View already exists"
````
```
Iceberg REST Compatibility Kit > JUnit Jupiter > RESTCompatibilityKitViewCatalogTests > updateViewLocationConflict() FAILED
    java.lang.AssertionError:
    Expecting throwable message:
      "View not found or action can_get_metadata forbidden for Principal(oidc~9410d0bf-4487-4177-a34f-af364cac0a59)"
    to contain:
      "View does not exist: ns.view"
```

I got some errors that returned a NotAuthorized exception, and this seems really strange to me. I will list all the cases that returned "Not authorized" and try to implement the tests on the Lakekeeper side to reproduce them.

```
Iceberg REST Compatibility Kit > JUnit Jupiter > RESTCompatibilityKitCatalogTests > testConcurrentReplaceTransactionSortOrderConflict() FAILED
    org.apache.iceberg.exceptions.NotAuthorizedException: Not authorized: Failed to authenticate
        at app//org.apache.iceberg.rest.ErrorHandlers$DefaultErrorHandler.accept(ErrorHandlers.java:234)
        at app//org.apache.iceberg.rest.ErrorHandlers$DefaultErrorHandler.accept(ErrorHandlers.java:212)
        at app//org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:215)
        at app//org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:299)
        at app//org.apache.iceberg.rest.BaseHTTPClient.post(BaseHTTPClient.java:100)
        at app//org.apache.iceberg.aws.s3.signer.S3V4RestSignerClient.sign(S3V4RestSignerClient.java:256)
```

Here are the results of the RCK run (https://gist.github.com/ndrluis/c2869d7f032808461fd51bde5182f8ee)

For the case of NamespaceNotFound -> NoSuchNamespaceException, I will open a PR in the next few days.

**Comment by ndrluis** [comment]
I ran another test with the minimal setup (without Authentication), and here are the results (https://gist.github.com/ndrluis/f805f0aa41dfba05441e1b91164b59f3). So when we have AuthN enabled, we receive a NotAuthorized error instead of the requirement error. I will open a new issue for this case, as we have some other cases that I think we need to understand to determine if it's a problem in the Lakekeeper.

About the text in the requirement exception, I know that it's a problem on the iceberg-rust side. I will open a discussion on the Iceberg Mailing list because if we want to use the RCK to test any REST implementation, we need to follow the same error message in all clients, or we need to rewrite the RCK tests to be more permissive

**Comment by ndrluis** [comment]
Mailing list thread about RCK and error messages
https://lists.apache.org/thread/rvxwxv1jzkxmhfb7ojzym08l44s7fqzp

**Comment by ndrluis** [comment]
I opened this PR  https://github.com/lakekeeper/lakekeeper/pull/1278 to solve the issue reported here. However, I will open other PRs with the RCK setup and some fixes. I believe we can change the scope of this issue to be broader in order to solve the incompatibility with the spec.
